extends: default

rules:
  document-start: disable
  document-end: disable
  indentation: disable
  line-length:
    max: 1000
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
    ignore: |
      .github/workflows/
  empty-lines:
    max-end: 1
  brackets:
    max-spaces-inside: 1
  braces:
    max-spaces-inside: 1
  comments: disable
  comments-indentation: disable
  truthy:
    check-keys: false
  octal-values:
    forbid-explicit-octal: true
    forbid-implicit-octal: true
