apiVersion: 1
datasources:
- name: WindTurbine
  isDefault: true
  type: elasticsearch
  access: proxy
  url: http://localhost:9200
  database: '[wind-turbine-]YYYY.MM.DD'
  jsonData:
    esVersion: 8.6.0
    interval: Daily
    timeField: '@timestamp'
