apiVersion: phenix.sandia.gov/v1
kind: Topology
metadata:
  name: soap-hil
  created: ""
  updated: ""
spec:
  nodes:
    - general:
        hostname: power-provider
      hardware:
        drives:
          - image: bennu.qc2
        os_type: linux
        memory: 512
        vcpus: 2
      network:
        interfaces:
          - address: 172.16.1.2
            gateway: 172.16.1.1
            mask: 16
            name: mgmt
            proto: static
            type: ethernet
            vlan: MGMT
      type: VirtualMachine
    - general:
        hostname: ignition
      hardware:
        drives:
          - image: ignition.qc2
        memory: 8192
        os_type: linux
        vcpus: 4
      network:
        interfaces:
          - address: 10.117.4.70
            gateway: 10.117.4.1
            mask: 24
            name: exp
            proto: static
            type: ethernet
            vlan: EXP
          - address: 172.16.1.3
            mask: 16
            name: mgmt
            proto: static
            type: ethernet
            vlan: MGMT
      commands:
        - exec bash -c "/usr/local/bin/ignition/gwcmd --restore /phenix/ignition.gwbk -y >> /var/log/gwcmd-restore.log 2>&1; /usr/local/bin/ignition/gwcmd -r >> /var/log/gwcmd-restore.log 2>&1"
      injections:
        - src: /phenix/topologies/soap-hil/injects/ignition/soap-hil_20240612.gwbk
          dst: /phenix/ignition.gwbk
      type: VirtualMachine
    - general:
        hostname: rtu-1
      hardware:
        drives:
          - image: bennu.qc2
        memory: 512
        os_type: linux
        vcpus: 1
      network:
        interfaces:
          - address: 10.117.4.101
            gateway: 10.117.4.1
            mask: 24
            name: exp
            proto: static
            type: ethernet
            vlan: EXP
          - address: 172.16.1.4
            mask: 16
            name: mgmt
            proto: static
            type: ethernet
            vlan: MGMT
      type: VirtualMachine
    - general:
        hostname: rtu-2
      hardware:
        drives:
          - image: bennu.qc2
        memory: 512
        os_type: linux
        vcpus: 1
      network:
        interfaces:
          - address: 10.117.4.102
            gateway: 10.117.4.1
            mask: 24
            name: exp
            proto: static
            type: ethernet
            vlan: EXP
          - address: 172.16.1.5
            mask: 16
            name: mgmt
            proto: static
            type: ethernet
            vlan: MGMT
      type: VirtualMachine
    - general:
        hostname: rtu-3
      hardware:
        drives:
          - image: bennu.qc2
        memory: 512
        os_type: linux
        vcpus: 1
      network:
        interfaces:
          - address: 10.117.4.103
            gateway: 10.117.4.1
            mask: 24
            name: exp
            proto: static
            type: ethernet
            vlan: EXP
          - address: 172.16.1.6
            mask: 16
            name: mgmt
            proto: static
            type: ethernet
            vlan: MGMT
      type: VirtualMachine
    - general:
        hostname: rtu-4
      hardware:
        drives:
          - image: bennu.qc2
        memory: 512
        os_type: linux
        vcpus: 1
      network:
        interfaces:
          - address: 10.117.4.104
            gateway: 10.117.4.1
            mask: 24
            name: exp
            proto: static
            type: ethernet
            vlan: EXP
          - address: 172.16.1.7
            mask: 16
            name: mgmt
            proto: static
            type: ethernet
            vlan: MGMT
      type: VirtualMachine
    - general:
        hostname: siren
      hardware:
        drives:
          - image: bennu.qc2
        memory: 512
        os_type: linux
        vcpus: 1
      network:
        interfaces:
          - address: 172.16.1.10
            mask: 16
            name: mgmt
            proto: static
            type: ethernet
            vlan: MGMT
      injections:
        - src: /phenix/topologies/soap-hil/injects/siren/s7-labjack.json
          dst: /siren/s7-labjack.json
        - src: /phenix/topologies/soap-hil/injects/siren/siren.json
          dst: /siren/siren.json
        - src: /phenix/topologies/soap-hil/injects/siren/siren-start.sh
          dst: /etc/phenix/startup/99_siren-start.sh
      type: VirtualMachine
      advanced:
        # attach labjack USB to siren VM via qemu
        # may need to adjust productid or vendorid
        # you can get these by running `lsusb -v` on the host
        qemu-append: "-device qemu-xhci -device usb-host,vendorid=0x0cd5,productid=0x0004"
    - general:
        hostname: netmonitor
      hardware:
        drives:
          - image: ubuntu-soaptools.qc2
        memory: 4096
        os_type: linux
        vcpus: 2
      network:
        interfaces:
          - address: 172.16.1.8
            gateway: 172.16.0.1
            mask: 16
            name: mgmt
            proto: static
            type: ethernet
            vlan: MGMT
          - address: 0.0.0.0 # 10.248.171.254/24
            mask: 0
            name: mirror
            proto: static
            type: ethernet
            vlan: MIRROR
      commands:
        - exec bash -c "systemctl start filebeat"
      injections:
        - src: /phenix/topologies/soap-hil/injects/netmonitor/filebeat_zeek_module.yml
          dst: /etc/filebeat/modules.d/zeek.yml
        - src: /phenix/topologies/soap-hil/injects/netmonitor/filebeat.yml
          dst: /etc/filebeat/filebeat.yml
        - src: /phenix/topologies/soap-hil/injects/netmonitor/zeek_node.cfg
          dst: /opt/zeek/etc/node.cfg

      type: VirtualMachine
    - general:
        hostname: attacker
      hardware:
        drives:
          - image: ubuntu-soaptools.qc2
        memory: 4096
        os_type: linux
        vcpus: 2
      injections:
        - src: /phenix/topologies/soap-hil/injects/attack/
          dst: /phenix/attack/
      network:
        interfaces:
          - address: 10.117.4.169
            mask: 24
            name: exp
            proto: static
            type: ethernet
            vlan: EXP
          - address: 172.16.1.9
            gateway: 172.16.0.1
            mask: 16
            name: mgmt
            proto: static
            type: ethernet
            vlan: MGMT
      type: VirtualMachine
