{
 "title": "Metric Dashboard Details",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Physical", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Power (MW)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "field:mw",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "field:voltage",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Cyber", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Alerts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 11 },
   "targets": [
    {
     "alias": "NIDS",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "HIDS",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Alert Level",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "rule.level", "id": "1", "type": "sum" }
     ],
     "query": "field:rule.level",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "port", "id": "1", "type": "sum" }
     ],
     "query": "*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "NIDS Alerts",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 20 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "HIDS Alerts",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 20 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "HIDS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 29 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "NIDS Alerts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 35 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SOAR",
   "type": "table",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 41 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}