{
 "title": "Wind Turbine Control Network",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Cyber Resilience",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "output == 'PASS'",
     "timeField": "@timestamp"
    },
    { "expression": "100 - ($A*7.69)", "type": "math" }
   ]
  },
  {
   "title": "Physical + Resilience",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "doc.Detection", "id": "1", "type": "avg" }
     ],
     "query": "doc.Id:'Score'",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Nozomi Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Severity Level 1 Entries",
   "type": "stat",
   "description": "Number of entries featuring severity level 1 from Logstash DS",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "severity:1",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Severity Level 1 Entries",
   "type": "stat",
   "description": "Number of entries featuring severity level 1 from Logstash DS",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "severity:1",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Severity Level 3 Entries",
   "type": "stat",
   "description": "Number of entries featuring severity level 3 from Logstash DS",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "severity:3",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Severity Level 4 Entries",
   "type": "stat",
   "description": "Number of entries featuring severity level 4 from Logstash DS",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "severity:4",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Severity Level 5 Entries",
   "type": "stat",
   "description": "Number of entries featuring severity level 5 from Logstash DS",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "severity:5",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Severity Level 6",
   "type": "stat",
   "description": "Number of entries featuring severity level 2 from Logstash DS",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "severity:6",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Severity Level 7",
   "type": "stat",
   "description": "Number of entries featuring severity level 2 from Logstash DS",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "severity:7",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Severity Level 8",
   "type": "stat",
   "description": "Number of entries featuring severity level 2 from Logstash DS",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "severity:8",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Severity Level 9",
   "type": "stat",
   "description": "Number of entries featuring severity level 2 from Logstash DS",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "severity:9",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Severity Level 10",
   "type": "stat",
   "description": "Number of entries featuring severity level 2 from Logstash DS",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "severity:10",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Live Alert and Metric Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Amount of Logs by Severity Level Over Time",
   "type": "timeseries",
   "description": "Show the count of logs that contain each severity level, represented over the given time period, queried from Logstash DS",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "alias": "Severity10",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "severity:10",
     "timeField": "@timestamp"
    },
    {
     "alias": "Severity9",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "severity:9",
     "timeField": "@timestamp"
    },
    {
     "alias": "Severity8",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "severity:8",
     "timeField": "@timestamp"
    },
    {
     "alias": "Severity7",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "severity:7",
     "timeField": "@timestamp"
    },
    {
     "alias": "Severity6",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "severity:6",
     "timeField": "@timestamp"
    },
    {
     "alias": "Severity5",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "severity:5",
     "timeField": "@timestamp"
    },
    {
     "alias": "Severity4",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "severity:4",
     "timeField": "@timestamp"
    },
    {
     "alias": "Severity3",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "severity:3",
     "timeField": "@timestamp"
    },
    {
     "alias": "Severity2",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "severity:2",
     "timeField": "@timestamp"
    },
    {
     "alias": "Severity1",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "severity:1",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Flowchart-System Critical Event Monitoring",
   "type": "agenty-flowcharting-panel",
   "description": "# System Critical Event Monitoring\n \nThis widget demonstrates combining multiple datasources into a single visualization panel as a comprehensive system monitoring solution.\n\n## Logstash WTG Network Events\n\nQueries A-V consist of one query against logstash for each WTG IP object present on the diagram, then associating each of those queries with its own Rule Mapping that causes the body of the diagram object to change color depending on the maximum severity of a log event for a particular machine within the given time frame: \n- light green(base, no records)\n- dark green (severity 1)\n- light yellow (severity 2)\n- dark yellow (severity 3)\n- light red (severity 4)\n- dark red (severity 5)\n\nQueries executed against the `logstash-*` datasource and are aliased as `WTG[1-30]-Severity-Max`. These queries are then associated with Mappings 1-30. Each WTG object is clickable and opens an additional dashboard that accepts the WTG IP Address as a variable.\n\n## Wazuh Critical Host Events\n\nQueries W-Z define how host machines (not WTG objects) are color coded according the the number of critical severity events within the given time frame. Critical severity events are defined as wazuh messages that alert with `data.win.system.level` >=5. However, currently(07/28/22) this field is treated as a string and we are unable to use it as a numeric value. Therefore, we are using the field `rule.level` as our severity value with and will change colors according the the following rules:\n- no color(base, <4)\n- orange warning(>=4)\n- red critical(>=7)\n\nQueries executed against the `wazuh-alerts-*` datasource and aliased as `[PNC1,PNC2,JH,WSC]-RuleLevel-Max`.\n",
   "gridPos": { "h": 14, "w": 8, "x": 12, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "WTG1-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.1",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG2-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.2",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG3-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.3",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG4-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.4",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG5-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.5",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG6-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.6",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG7-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.7",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG8-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.8",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG9-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.9",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG10-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.10",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG11-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.11",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG12-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.12",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG13-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.13",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG14-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.14",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG15-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.15",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG16-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.16",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG17-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.17",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG18-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.18",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG19-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.19",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG20-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.20",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG21-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.21",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG22-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.22",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG23-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.23",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG24-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.24",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG25-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.25",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG26-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.26",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG27-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.27",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG28-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.28",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG29-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.29",
     "timeField": "@timestamp"
    },
    {
     "alias": "WTG30-Severity-Max",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "severity", "id": "1", "type": "max" }
     ],
     "query": "destinationAddress:192.168.100.30",
     "timeField": "@timestamp"
    },
    {
     "alias": "PNC1-RuleLevel-Max",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "rule.level", "id": "1", "type": "max" }
     ],
     "query": "agent.ip:192.168.40.100",
     "timeField": "@timestamp"
    },
    {
     "alias": "PNC2-RuleLevel-Max",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "rule.level", "id": "1", "type": "max" }
     ],
     "query": "agent.ip:192.168.50.100",
     "timeField": "@timestamp"
    },
    {
     "alias": "JH-RuleLevel-Max",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "rule.level", "id": "1", "type": "max" }
     ],
     "query": "agent.ip:192.168.60.100",
     "timeField": "@timestamp"
    },
    {
     "alias": "WSC-RuleLevel-Max",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "rule.level", "id": "1", "type": "max" }
     ],
     "query": "agent.ip:192.168.100.100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Detection Value Per Resilience Metric Over Time",
   "type": "timeseries",
   "description": "Display the detection value for each resilience metric, graphed over a period of time. WARNING: this will not work until the bennu index \"Detection\" field is defined as a double/float.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "alias": "Avg_Resilience_Detection",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "doc.Detection", "id": "1", "type": "avg" }
     ],
     "query": "doc.Id:\"Resilience\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Avg_Physical_Detection",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "doc.Detection", "id": "1", "type": "avg" }
     ],
     "query": "doc.Id:\"Physical\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Avg_Score_Detection",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "doc.Detection", "id": "1", "type": "avg" }
     ],
     "query": "doc.Id:\"Score\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Resilience Metric Table",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 12, "y": 34 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "Time"
    }
   ]
  }
 ]
}