apiVersion: phenix.sandia.gov/v1
kind: Image
metadata:
    name: ubuntu-soaptools
spec:
    compress: true
    components:
        - main
        - restricted
        - universe
        - multiverse
    format: qcow2
    include_miniccc: false
    include_protonuke: false
    mirror: http://us.archive.ubuntu.com/ubuntu/
    overlays: null
    packages:
        - initramfs-tools
        - net-tools
        - isc-dhcp-client
        - openssh-server
        - init
        - iputils-ping
        - vim
        - less
        - netbase
        - curl
        - ifupdown
        - dbus
        - linux-image-generic
        - linux-headers-generic
        - xorg
        - xinit
        - dbus-x11
        - libpython3-stdlib
        - libexpat1
        - zlib1g
        - libc6
        - python3-minimal
        - python3
        - python3-ply
        - python3-pycparser
        - python3-cffi
        - python3-cffi-backend
        - xfce4
        - xserver-xorg
        - xserver-xorg-input-all
        - xserver-xorg-video-qxl
        - xserver-xorg-video-vesa
        - qemu-guest-agent

    ramdisk: false
    release: jammy
    script_order:
        - POSTBUILD_GUI_AND_TOOLS
        - POSTBUILD_FILEBEAT_INSTALL
        - POSTBUILD_ZEEK_INSTALL
        - POSTBUILD_MSFCONSOLE
        - POSTBUILD_APT_CLEANUP
        - POSTBUILD_PIP
        - POSTBUILD_NO_ROOT_PASSWD
        - POSTBUILD_PHENIX_HOSTNAME
        - POSTBUILD_PHENIX_BASE
    scripts:
        POSTBUILD_APT_CLEANUP: |
            apt clean || apt-get clean || echo "unable to clean apt cache"
        POSTBUILD_GUI_AND_TOOLS: |
            cat > /etc/apt/sources.list.d/updates.list <<EOF
            deb http://us.archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
            deb http://us.archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
            deb http://us.archive.ubuntu.com/ubuntu jammy-security main restricted universe multiverse
            EOF
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y --install-recommends xubuntu-core epiphany-browser wireshark-gtk python3-pip python-is-python3 micro
        POSTBUILD_NO_ROOT_PASSWD: |
            sed -i 's/nullok_secure/nullok/' /etc/pam.d/common-auth
            sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
            sed -i 's/#PermitEmptyPasswords no/PermitEmptyPasswords yes/' /etc/ssh/sshd_config
            sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
            sed -i 's/PermitEmptyPasswords no/PermitEmptyPasswords yes/' /etc/ssh/sshd_config
            passwd -d root
        POSTBUILD_PHENIX_BASE: |
            cat > /etc/systemd/system/miniccc.service <<EOF
            [Unit]
            Description=miniccc
            [Service]
            ExecStart=/opt/minimega/bin/miniccc -v=false -serial /dev/virtio-ports/cc -logfile /var/log/miniccc.log
            [Install]
            WantedBy=multi-user.target
            EOF
            cat > /etc/systemd/system/phenix.service <<EOF
            [Unit]
            Description=phenix startup service
            After=network.target systemd-hostnamed.service
            [Service]
            Environment=LD_LIBRARY_PATH=/usr/local/lib
            ExecStart=/usr/local/bin/phenix-start.sh
            RemainAfterExit=true
            StandardOutput=journal
            Type=oneshot
            [Install]
            WantedBy=multi-user.target
            EOF
            mkdir -p /etc/systemd/system/multi-user.target.wants
            ln -s /etc/systemd/system/miniccc.service /etc/systemd/system/multi-user.target.wants/miniccc.service
            ln -s /etc/systemd/system/phenix.service /etc/systemd/system/multi-user.target.wants/phenix.service
            mkdir -p /usr/local/bin
            cat > /usr/local/bin/phenix-start.sh <<EOF
            #!/bin/bash
            for file in /etc/phenix/startup/*; do
            	echo \$file
            	bash \$file
            done
            EOF
            chmod +x /usr/local/bin/phenix-start.sh
            mkdir -p /etc/phenix/startup
        POSTBUILD_PHENIX_HOSTNAME: |
            echo "phenix" > /etc/hostname
            sed -i 's/127.0.1.1 .*/127.0.1.1 phenix/' /etc/hosts
            cat > /etc/motd <<EOF

            ██████╗ ██╗  ██╗███████╗███╗  ██╗██╗██╗  ██╗
            ██╔══██╗██║  ██║██╔════╝████╗ ██║██║╚██╗██╔╝
            ██████╔╝███████║█████╗  ██╔██╗██║██║ ╚███╔╝
            ██╔═══╝ ██╔══██║██╔══╝  ██║╚████║██║ ██╔██╗
            ██║     ██║  ██║███████╗██║ ╚███║██║██╔╝╚██╗
            ╚═╝     ╚═╝  ╚═╝╚══════╝╚═╝  ╚══╝╚═╝╚═╝  ╚═╝

            EOF
            echo "\nBuilt with phenix image on $(date)\n\n" >> /etc/motd
        POSTBUILD_PIP: |
            set -e
            pip3 install python-snap7==1.3 dnp3-python==0.2.3b3
        POSTBUILD_FILEBEAT_INSTALL: |
            set -e
            # if you are behind a proxy and get certificate errors, change `curl` to `curl --insecure`
            curl -LO https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.17.21-amd64.deb
            dpkg -i filebeat-7.17.21-amd64.deb
        POSTBUILD_ZEEK_INSTALL: |
            set -e

            ## uncomment the lines below if your are behind a proxy and get certificate errors with apt
            # sudo tee /etc/apt/apt.conf.d/99-no-verify  <<EOF
            # Acquire::https::Verify-Peer "false";
            # Acquire::https::Verify-Host "false";
            # EOF

            echo 'deb http://download.opensuse.org/repositories/security:/zeek/xUbuntu_22.04/ /' | tee /etc/apt/sources.list.d/security:zeek.list

            # if you are behind a proxy and get certificate errors, change `curl` to `curl --insecure`
            curl -fsSL https://download.opensuse.org/repositories/security:zeek/xUbuntu_22.04/Release.key | gpg --dearmor | tee /etc/apt/trusted.gpg.d/security_zeek.gpg > /dev/null
            apt update
            DEBIAN_FRONTEND=noninteractive apt install zeek-6.0 -y
        POSTBUILD_MSFCONSOLE: |
            # if you are behind a proxy and get certificate errors, change `curl` to `curl --insecure`
            curl -L https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb | bash

    size: 50G
    variant: minbase
